# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBr0G7PXQEDOn1Of_0tuxFf67Dw-WdNG

# LSTM-arithmetic

## Dataset
- [Arithmetic dataset](https://drive.google.com/file/d/1cMuL3hF9jefka9RyF4gEBIGGeFGZYHE-/view?usp=sharing)
"""

# ! pip install seaborn
# ! pip install opencc
# ! pip install -U scikit-learn

import numpy as np
import pandas as pd
import torch
import torch.nn
import torch.nn.utils.rnn
import torch.utils.data
import matplotlib.pyplot as plt
import seaborn as sns
import opencc
import os
from sklearn.model_selection import train_test_split

data_path = './data'

df_train = pd.read_csv(os.path.join(data_path, 'arithmetic_train.csv'))
df_eval = pd.read_csv(os.path.join(data_path, 'arithmetic_eval.csv'))
df_train.head()

# transform the input data to string
df_train['tgt'] = df_train['tgt'].apply(lambda x: str(x))
df_train['src'] = df_train['src'].add(df_train['tgt'])
df_train['len'] = df_train['src'].apply(lambda x: len(x))

df_eval['tgt'] = df_eval['tgt'].apply(lambda x: str(x))

"""# Build Dictionary
 - The model cannot perform calculations directly with plain text.
 - Convert all text (numbers/symbols) into numerical representations.
 - Special tokens
    - '&lt;pad&gt;'
        - Each sentence within a batch may have different lengths.
        - The length is padded with '&lt;pad&gt;' to match the longest sentence in the batch.
    - '&lt;eos&gt;'
        - Specifies the end of the generated sequence.
        - Without '&lt;eos&gt;', the model will not know when to stop generating.
"""

# This char_to_id I made based on math's order of operations
# The first two I take from the examples, then followed by:
# Parantheses, Multiplication, Addition & Substraction, Then all of the number, and the last one is equal sign
# Reference: https://en.wikipedia.org/wiki/Order_of_operations
char_to_id = {
    '<pad>': 0,
    '<eos>': 1,
    '(': 2,
    ')': 3,
    '*': 4,
    '+': 5,
    '-': 6,
    '0': 7,
    '1': 8,
    '2': 9,
    '3': 10,
    '4': 11,
    '5': 12,
    '6': 13,
    '7': 14,
    '8': 15,
    '9': 16,
    '=': 17,
}
# Just reverse the position
id_to_char = {
    0: '<pad>',
    1: '<eos>',
    2: '(',
    3: ')',
    4: '*',
    5: '+',
    6: '-',
    7: '0',
    8: '1',
    9: '2',
    10: '3',
    11: '4',
    12: '5',
    13: '6',
    14: '7',
    15: '8',
    16: '9',
    17: '='
}

# write your code here
# Build a dictionary and give every token in the train dataset an id
# The dictionary should contain <eos> and <pad>
# char_to_id is to conver charactors to ids, while id_to_char is the opposite

vocab_size = len(char_to_id)
print('Vocab size{}'.format(vocab_size))

"""# Data Preprocessing
 - The data is processed into the format required for the model's input and output. (End with \<eos\> token)

"""

# Write your code here
# From each row in the dataset, access each char, and convert it to id. After that, add it with <eos>
# Reference 1: https://stackoverflow.com/questions/16476924/how-can-i-iterate-over-rows-in-a-pandas-dataframe
# Reference 2: https://www.geeksforgeeks.org/pandas/adding-new-column-to-existing-dataframe-in-pandas/
char_id_list_train = []
for index, row in df_train.iterrows():
    char_id = []
    for char in row['src']:
        char_id.append((char_to_id[char]))
    char_id.append((char_to_id['<eos>']))
    char_id_list_train.append(char_id)

df_train['char_id_list'] = char_id_list_train

char_id_list_eval = []
for index, row in df_eval.iterrows():
    char_id = []
    for char in row['src']:
        char_id.append((char_to_id[char]))
    char_id.append((char_to_id['<eos>']))
    char_id_list_eval.append(char_id)

df_eval['char_id_list'] = char_id_list_eval

df_train.head()

# From the label_id_list_train and label_id_list_eval, access each value,
# and change everything before '=', including the '=' to '<pad>', which is 0 in our case
# Reference: https://stackoverflow.com/questions/176918/how-can-i-find-the-index-for-a-given-item-in-a-list
label_id_list_train = []
for row in char_id_list_train:
    label_id = row.copy()
    index = row.index(char_to_id['='])
    for i in range(index + 1):
        label_id[i] = char_to_id['<pad>']
    label_id_list_train.append(label_id)

df_train['label_id_list'] = label_id_list_train

label_id_list_eval = []
for row in char_id_list_eval:
    label_id = row.copy()
    index = row.index(char_to_id['='])
    for i in range(index + 1):
        label_id[i] = char_to_id['<pad>']
    label_id_list_eval.append(label_id)

df_eval['label_id_list'] = label_id_list_eval
# print(df_train.head())
"""# Hyper Parameters

|Hyperparameter|Meaning|Value|
|-|-|-|
|`batch_size`|Number of data samples in a single batch|64|
|`epochs`|Total number of epochs to train|10|
|`embed_dim`|Dimension of the word embeddings|256|
|`hidden_dim`|Dimension of the hidden state in each timestep of the LSTM|256|
|`lr`|Learning Rate|0.001|
|`grad_clip`|To prevent gradient explosion in RNNs, restrict the gradient range|1|
"""

batch_size = 128
epochs = 20
embed_dim = 64
hidden_dim = 512
lr = 0.0008
grad_clip = 1

"""# Data Batching
- Use `torch.utils.data.Dataset` to create a data generation tool called  `dataset`.
- The, use `torch.utils.data.DataLoader` to randomly sample from the `dataset` and group the samples into batches.

- Example: 1+2-3=0
    - Model input: 1 + 2 - 3 = 0
    - Model output: / / / / / 0 &lt;eos&gt;  (the '/' can be replaced with &lt;pad&gt;)
    - The key for the model's output is that the model does not need to predict the next character of the previous part. What matters is that once the model sees '=', it should start generating the answer, which is '0'. After generating the answer, it should also generate&lt;eos&gt;
"""

class Dataset(torch.utils.data.Dataset):
    def __init__(self, sequences):
        self.sequences = sequences

    def __len__(self):
        # return the amount of data
        return len(self.sequences) # Write your code here

    def __getitem__(self, index):
        # Extract the input data x and the ground truth y from the data
        # For the input (x), based on the instruction, there's no <eos>, so I remove it (located at the end of the list)
        # For the output (y), because it will predict the next token, then I remove the value at the first index
        # Reference: https://www.tensorflow.org/text/tutorials/text_generation
        x = self.sequences['char_id_list'][index][:-1] # Write your code here
        y = self.sequences['label_id_list'][index][1:] # Write your code here
        return x, y

# collate function, used to build dataloader
def collate_fn(batch):
    batch_x = [torch.tensor(data[0]) for data in batch]
    batch_y = [torch.tensor(data[1]) for data in batch]
    batch_x_lens = torch.LongTensor([len(x) for x in batch_x])
    batch_y_lens = torch.LongTensor([len(y) for y in batch_y])

    # Pad the input sequence
    pad_batch_x = torch.nn.utils.rnn.pad_sequence(batch_x,
                                                  batch_first=True,
                                                  padding_value=char_to_id['<pad>'])

    pad_batch_y = torch.nn.utils.rnn.pad_sequence(batch_y,
                                                  batch_first=True,
                                                  padding_value=char_to_id['<pad>'])

    return pad_batch_x, pad_batch_y, batch_x_lens, batch_y_lens

ds_train = Dataset(df_train[['char_id_list', 'label_id_list']])

# Build dataloader of train set and eval set, collate_fn is the collate function
# Reference 1: https://docs.pytorch.org/docs/stable/data.html
# Reference 2: https://stackoverflow.com/questions/77991685/should-the-pytorch-validation-and-test-loaders-shuffle-the-data
dl_train = torch.utils.data.DataLoader(dataset=ds_train, batch_size=batch_size, shuffle=True, collate_fn=collate_fn) # Write your code here

"""# Model Design

## Execution Flow
1. Convert all characters in the sentence into embeddings.
2. Pass the embeddings through an LSTM sequentially.
3. The output of the LSTM is passed into another LSTM, and additional layers can be added.
4. The output from all time steps of the final LSTM is passed through a Fully Connected layer.
5. The character corresponding to the maximum value across all output dimensions is selected as the next character.

## Loss Function
Since this is a classification task, Cross Entropy is used as the loss function.

## Gradient Update
Adam algorithm is used for gradient updates.
"""

class CharRNN(torch.nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super(CharRNN, self).__init__()

        self.embedding = torch.nn.Embedding(num_embeddings=vocab_size,
                                            embedding_dim=embed_dim,
                                            padding_idx=char_to_id['<pad>'])

        self.rnn_layer1 = torch.nn.LSTM(input_size=embed_dim,
                                        hidden_size=hidden_dim,
                                        batch_first=True)

        self.rnn_layer2 = torch.nn.LSTM(input_size=hidden_dim,
                                        hidden_size=hidden_dim,
                                        batch_first=True)

        self.linear = torch.nn.Sequential(torch.nn.Linear(in_features=hidden_dim,
                                                          out_features=hidden_dim),
                                          torch.nn.ReLU(),
                                          torch.nn.Linear(in_features=hidden_dim,
                                                          out_features=vocab_size))

    def forward(self, batch_x, batch_x_lens):
        return self.encoder(batch_x, batch_x_lens)

    # The forward pass of the model
    def encoder(self, batch_x, batch_x_lens):
        batch_x = self.embedding(batch_x)

        batch_x = torch.nn.utils.rnn.pack_padded_sequence(batch_x,
                                                          batch_x_lens,
                                                          batch_first=True,
                                                          enforce_sorted=False)

        batch_x, _ = self.rnn_layer1(batch_x)
        batch_x, _ = self.rnn_layer2(batch_x)

        batch_x, _ = torch.nn.utils.rnn.pad_packed_sequence(batch_x,
                                                            batch_first=True)

        batch_x = self.linear(batch_x)

        return batch_x

    def generator(self, start_char, max_len=200):
        with torch.no_grad():
            char_list = [char_to_id[c] for c in start_char]

            next_char = None
            # Get the device variable
            # Reference 1: https://stackoverflow.com/questions/58926054/how-to-get-the-device-type-of-a-pytorch-module-conveniently
            # Reference 2: https://blog.csdn.net/m0_46483236/article/details/122112276
            device = next(self.parameters()).device
            while len(char_list) < max_len:
                # Write your code here
                # Reference: https://www.kaggle.com/code/wen731/machinelearning
                # Pack the char_list to tensor
                x = torch.tensor(char_list).unsqueeze(0).to(device)
                # Input the tensor to the embedding layer, LSTM layers, linear respectively
                # Input tensor to embedding layer
                x = self.embedding(x)
                # Input tensor to RNN layers
                # Reference: https://discuss.pytorch.org/t/troubleshooting-my-lstm/94275
                x, _ = self.rnn_layer1(x)
                x, _ = self.rnn_layer2(x)

                # Input tensor to linear -> obtain y
                # Reference: https://github.com/casadi/casadi/discussions/3824
                y = self.linear(x[:, -1, :]) # Obtain the next token prediction y

                # Reference: https://blog.csdn.net/ashen_0nee/article/details/127099799
                next_char = torch.argmax(y).item() # Use argmax function to get the next token prediction

                if next_char == char_to_id['<eos>']:
                    break

                char_list.append(next_char)

            return [id_to_char[ch_id] for ch_id in char_list]

torch.manual_seed(2)

# Reference: https://www.kaggle.com/code/subhajeetdas/1-pytorch-cuda-check
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') # Write your code here. Specify a device (cuda or cpu)

model = CharRNN(vocab_size,
                embed_dim,
                hidden_dim)

# Reference: https://www.kaggle.com/code/wen731/machinelearning
criterion = torch.nn.CrossEntropyLoss(ignore_index=char_to_id['<pad>'], reduction='mean') # Write your code here. Cross-entropy loss function. The loss function should ignore <pad>
optimizer = torch.optim.Adam(model.parameters(), lr=lr) # Write your code here. Use Adam or AdamW for Optimizer


"""# Training
1. The outer `for` loop controls the `epoch`
    1. The inner `for` loop uses `data_loader` to retrieve batches.
        1. Pass the batch to the `model` for training.
        2. Compare the predicted results `batch_pred_y` with the true labels `batch_y` using Cross Entropy to calculate the loss `loss`
        3. Use `loss.backward` to automatically compute the gradients.
        4. Use `torch.nn.utils.clip_grad_value_` to limit the gradient values between `-grad_clip` &lt; and &lt; `grad_clip`.
        5. Use `optimizer.step()` to update the model (backpropagation).
2.  After every `1000` batches, output the current loss to monitor whether it is converging.
"""

from tqdm import tqdm
from copy import deepcopy
import time

model = model.to(device)
model.train()
i = 0
for epoch in range(1, epochs+1):
    # The process bar
    bar = tqdm(dl_train, desc=f"Train epoch {epoch}")
    for batch_x, batch_y, batch_x_lens, batch_y_lens in bar:
        # Write your code here
        # Clear the gradient
        # Reference: https://www.kaggle.com/code/wen731/machinelearning
        optimizer.zero_grad()

        # Move the data to device (prefer the GPU)
        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)

        batch_pred_y = model(batch_x, batch_x_lens)
        # ChatGPT was helping me to generate this line. Its used to change the dimension order
        # If we not using this, there'll be an error: Expected target size [64, 18], got [64, 16]
        batch_pred_y = batch_pred_y.transpose(1, 2)

        # Write your code here
        # Input the prediction and ground truths to loss function
        loss = criterion(batch_pred_y, batch_y)
        # Back propagation
        loss.backward()

        torch.nn.utils.clip_grad_value_(model.parameters(), grad_clip) # gradient clipping

        # Write your code here
        # Optimize parameters in the model
        optimizer.step()

        i+=1
        if i%50==0:
            bar.set_postfix(loss = loss.item())

    # Evaluate your model
    matched = 0
    total = 0
    bar_eval = tqdm(df_eval.iterrows(), total=len(df_eval), desc=f"Validation epoch {epoch}")
    for _, row in bar_eval:
        batch_x = row['src']
        batch_y = row['tgt']

        prediction = model.generator(batch_x) # An example of using generator: model.generator('1+1=')

        # Write your code here. Input the batch_x to the model and generate the predictions
        # Find the '=' index position
        equal_index = prediction.index('=')
        prediction_string = ""
        # Looping, started from +1 index after '=' index until the length of the list
        for i in range(equal_index + 1, len(prediction)):
            # Make sure the value at i-index not <eos>
            if prediction[i] != '<eos>':
                # Add to the string
                prediction_string += prediction[i]

        # Write your code here.
        # Check whether the prediction match the ground truths
        # Compute exact match (EM) on the eval dataset
        if prediction_string == batch_y:
            matched += 1
        # EM = correct/total
        total += 1
        bar_eval.set_postfix(accuracy = matched/total)

    print(matched/total)
